<a href="https://colab.research.google.com/github/TutkuDuruer/GroupBy/blob/main/Tutku_Duruer_Homework_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:

import pandas as pd
import numpy as np
from scipy.stats import ttest_1samp
from statsmodels.stats.proportion import proportions_ztest
from scipy import stats
import seaborn as sns
import sklearn.datasets

In [37]:
#1-Please apply each of 4 hypothesis testing methods (one/two proportions/means) on the heart dataset for the columns/variables
#that you will determine

1.Cİ VERİ SETİ

In [38]:
data=pd.read_csv("/content/heart.csv")
data

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [63]:
# One Proportion Test:
#Null hiptotesis : The person's maximum heart rate > 150 olan kişilerin sayısı %60 oranındadır.
#thalach==The person's maximum heart rate
sample_mean = 0.60

stats.ttest_1samp(data["thalach"], sample_mean)
#aalfa degeri p degerinden büyüktür. Null hipotezi ret edilir.

TtestResult(statistic=206.67781212641876, pvalue=0.0, df=1024)

In [72]:
# Two Proportions Testing

G1 = data[data["sex"] == 1]["thalach"]
G2 = data[data["sex"] == 0]["thalach"]

stats.ttest_ind(G1, G2)
#pvalue alfa değerinden büyük olduğu için null hipotezi kabul edilir.
#Erkek ve kadın grupları arasında thalach değerinin istatistiksel olarak anlamlı bir fark yoktur.

Ttest_indResult(statistic=-1.5808436320867354, pvalue=0.1142229084355055)

In [68]:
#One Mean Test:
#Null hiptotesis: thalach alanının ortalama degeri 0.8'dır.

sample_mean = 0.8
stats.ttest_1samp(data["thalach"], sample_mean)
##Alfa degeri p degerinden büyüktür.Null hipotezi ret edilir.

TtestResult(statistic=206.39948468459883, pvalue=0.0, df=1024)

2. VERİ SETİ

In [86]:
iris = sns.load_dataset('iris')
iris

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [89]:
#
sp_ln = iris["sepal_length"].to_numpy()

stats.ttest_1samp(sp_ln, 0)

#task 2

seto = iris[iris.species == "setosa" ]["sepal_length"].to_numpy()
ver = iris[iris.species == "versicolor" ]["sepal_length"].to_numpy()

w = stats.ttest_ind(seto, ver, equal_var=False)



#task 3
seto1= iris[iris.species == "setosa"]["petal_width"].to_numpy()
virgi = iris[iris.species == "virginica"]["petal_width"].to_numpy()
stats.ttest_rel(seto1, virgi)


#task 4

vers = iris[iris.species == "versicolor"]["sepal_length"].to_numpy()
virg = iris[iris.species == "virginica"]["petal_length"].to_numpy()
stats.pearsonr(vers,virg)
seto1

array([0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2, 0.2, 0.1,
       0.1, 0.2, 0.4, 0.4, 0.3, 0.3, 0.3, 0.2, 0.4, 0.2, 0.5, 0.2, 0.2,
       0.4, 0.2, 0.2, 0.2, 0.2, 0.4, 0.1, 0.2, 0.2, 0.2, 0.2, 0.1, 0.2,
       0.2, 0.3, 0.3, 0.2, 0.6, 0.4, 0.3, 0.2, 0.2, 0.2, 0.2])

3.cü Data Seti Vote ile ilgili olan

In [44]:
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/voting-records/house-votes-84.data
column_headers = ['party','handicapped-infants','water-project',
                  'budget','physician-fee-freeze', 'el-salvador-aid',
                  'religious-groups','anti-satellite-ban',
                  'aid-to-contras','mx-missile','immigration',
                  'synfuels', 'education', 'right-to-sue','crime','duty-free',
                  'south-africa']

a= pd.read_csv('house-votes-84.data', names=column_headers)
a= a.replace({"y": 1, "n": 0, "?": np.NaN})
a.head()

--2023-07-21 18:11:20--  https://archive.ics.uci.edu/ml/machine-learning-databases/voting-records/house-votes-84.data
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified
Saving to: ‘house-votes-84.data.1’

house-votes-84.data     [ <=>                ]  17.75K  --.-KB/s    in 0.008s

2023-07-21 18:11:21 (2.07 MB/s) - ‘house-votes-84.data.1’ saved [18171]

,party,handicapped-infants,water-project,budget,physician-fee-freeze,el-salvador-aid,religious-groups,anti-satellite-ban,aid-to-contras,mx-missile,immigration,synfuels,education,right-to-sue,crime,duty-free,south-africa
0,republican,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,NaN,1.0,1.0,1.0,0.0,1.0
1,republican,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,NaN
2,democrat,NaN,1.0,1.0,NaN,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0
3,democrat,0.0,1.0,1.0,0.0,NaN,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
4,democrat,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,NaN,1.0,1.0,1.0,1.0

In [45]:
a.isnull().sum()

party                     0
handicapped-infants      12
water-project            48
budget                   11
physician-fee-freeze     11
el-salvador-aid          15
religious-groups         11
anti-satellite-ban       14
aid-to-contras           15
mx-missile               22
immigration               7
synfuels                 21
education                31
right-to-sue             25
crime                    17
duty-free                28
south-africa            104
dtype: int64

In [49]:
#One Proportion Testing
#physician-fee-freeze columunudaki nan degerleri  yok ettim.
a_without_nan = a["physician-fee-freeze"].dropna()

# H0: physician-fee-freeze'a yes diyenlerin sayısı %80'dir
sample_mean = 0.8
stats.ttest_1samp(a_without_nan, sample_mean)

#pvalue alfa'dan küçük olduğu için null hipotezini red  ediyoruz ve istatistiksel olarak anlamlı bir fark  vardır.

TtestResult(statistic=-15.954600122825275, pvalue=3.3605294182518916e-45, df=423)

In [52]:
#Two Proportions Test
#Nan degerlerini colum üzerinden attım.
category1 = a[a["party"] == "republican"]["physician-fee-freeze"].dropna()
category2 = a[a["party"] == "democrat"]["physician-fee-freeze"].dropna()

stats.ttest_ind(category1, category2)
#bu teste iki farklı gruba ait aynı ögeleri karşılaştırmak için kullanılır.
#pvalue alfa'dan küçük olduğu için  aralarında anlamlı bir fark vardır. Null hipotezini geçersiz sayılır.

Ttest_indResult(statistic=49.367081573014055, pvalue=1.994262314074572e-177)

In [53]:
#One Mean Test
# physician-fee-freeze columnının ortalaması  0.8'dir
sample_mean = 0.8
stats.ttest_1samp(a_without_nan, sample_mean)
#pvalue değeri alfadan küçük olduğu için aralarında anamlı bir fark vardır  null hipotezi rededilir.

TtestResult(statistic=-15.954600122825275, pvalue=3.3605294182518916e-45, df=423)